services:
  # 1. Backend Service
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - backend_storage:/app/storage
    depends_on:
      - db
    restart: always

  # 2. Frontend Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always

  # 3. Database Service
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/database.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  db_data:
  backend_storage:
  backend_node_modules: